language: node_js
node_js:
    - "node"
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
cache:
    - yarn
    - npm
script:
    - yarn install --frozen-lockfile
    - yarn build
    - yarn test
    - yarn coverage
after_success:
    - cat ./packages/mobx-state-tree/coverage/lcov.info | ./packages/node_modules/coveralls/bin/coveralls.js
