language: node_js
node_js:
    - "node"
cache:
    - yarn
script:
    - yarn build
    - yarn test
after_success:
    - cat ./packages/mobx-state-tree/coverage/lcov.info | ./packages/node_modules/coveralls/bin/coveralls.js
