version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:latest
        working_directory: ~/mst
        steps:
            - checkout

            - restore_cache:
                  name: restore .cache/yarn
                  keys:
                      - yarn-cache
            - restore_cache:
                  name: restore node_modules
                  keys:
                      - node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - run: yarn install --frozen-lockfile
            - save_cache:
                  name: cache .cache/yarn
                  key: yarn-cache
                  paths:
                      - ~/.cache/yarn
            - save_cache:
                  name: cache node_modules
                  key: node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules

            - run: yarn build
            - run: yarn test
            - run: yarn coverage
